import "@ant-design/v5-patch-for-react-19";

import type { Metadata } from "next";
import "./globals.css";
import AntdRegistry from "../lib/AntdRegistry";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
